# Source: wave/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: wave
    release: "wave"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'cluster'
  name: wave-wave
  annotations:
    meta.helm.sh/release-name: 'wave'
    meta.helm.sh/release-namespace: 'secret-infra'
    kapp.k14s.io/change-group: 'apps.jenkins-x.io/pusher-wave'
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - list
  - get
  - update
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  verbs:
  - list
  - get
  - update
  - patch
  - watch
- verbs:
  - '*'
  apiGroups:
  - coordination.k8s.io
  resources:
  - leases
